#!/usr/bin/env python3
"""
mdToTypst.py - Convert a Lyrical .md/.poem file to a Typst chapbook document.

Extracts the poem body (everything between @@poem / @@poem:start and @@poem:end
or end-of-file), strips Lyrical directives and Markdown section headings, and
wraps the result in a #poem("...") call inside a chapBook.typ document.

Usage:
    python mdToTypst.py <input_file> [output_file]

Example:
    python mdToTypst.py tyger.poem          # writes tyger.typ
    python mdToTypst.py poem02.md out.typ
"""

import re
import sys
import os


# ── Parsing ────────────────────────────────────────────────────────────────

def parse_front_matter(content):
    match = re.search(r'^---\n(.*?)\n---', content, re.DOTALL)
    if not match:
        return {}, content
    metadata = {}
    for line in match.group(1).split('\n'):
        if ':' in line:
            key, value = line.split(':', 1)
            metadata[key.strip()] = value.split('#')[0].strip()
    return metadata, content[match.end():].strip()


def extract_poem_lines(body):
    """
    Return the poem lines and any attribution lines from the body.

    Rules:
    - Collection starts at the first @@poem / @@poem:start directive.
    - Collection stops at @@poem:end (or EOF).
    - All other @@ directives are consumed silently.
    - Markdown section headings (# Heading) outside/inside poem block are dropped.
    - Attribution lines (~>) are pulled out separately and rendered after the poem.
    - Alignment prefixes (-> and -><) are stripped; content is kept.
    - Colon-indentation prefixes (:, ::, …) are stripped; content is kept.
    - Markdown heading markers at the start of a line (#word) are stripped.
    - Continuation markers (+) and inline markers (%%small caps%%, ||) are left
      as-is; chapBook.typ's poem() interprets them when typesetting.
    - Blank lines are preserved as stanza breaks.
    """
    lines = body.split('\n')
    poem_lines = []
    attributions = []
    in_poem = False

    for line in lines:
        s = line.strip()

        # Strip inline comments from directive-looking lines
        if s.startswith('@@') or s.startswith('->'):
            ci = s.find(' #')
            if ci != -1:
                s = s[:ci].strip()

        # Poem mode control
        if s in ('@@poem', '@@poem:start'):
            in_poem = True
            continue
        if s == '@@poem:end':
            in_poem = False
            continue

        # Skip all other directives regardless of mode
        if s.startswith('@@'):
            continue

        # Skip Markdown section headings (# Title, ## Sub, etc.)
        if re.match(r'^#{1,6}\s', s):
            continue

        # Attribution / byline — collected separately, rendered after the poem.
        # Works inside or outside @@poem, matching the other two backends —
        # a signature line often follows @@poem:end rather than preceding it.
        if s.startswith('~>'):
            attributions.append(s[2:])
            continue

        # Only emit lines once inside the poem section
        if not in_poem:
            continue

        # Strip alignment prefixes — content is kept, alignment context is lost
        if s.startswith('-><'):
            s = s[3:]
        elif s.startswith('->'):
            s = s[2:]

        # Strip colon-based indentation prefixes
        colon = re.match(r'^(:+)(.*)', s)
        if colon:
            s = colon.group(2)

        # Strip stray Markdown heading markers (#word without a space, e.g. #Tyger)
        hash_word = re.match(r'^(#+)(\S.*)', s)
        if hash_word:
            s = hash_word.group(2)

        poem_lines.append(s)

    # Trim leading / trailing blank lines
    while poem_lines and poem_lines[0] == '':
        poem_lines.pop(0)
    while poem_lines and poem_lines[-1] == '':
        poem_lines.pop()

    return poem_lines, attributions


# ── Typst generation ────────────────────────────────────────────────────────

def escape_typst(text):
    """Escape characters that are special inside a Typst string literal."""
    text = text.replace('\\', '\\\\')
    text = text.replace('"', '\\"')
    return text


def metre_from_metadata(metadata):
    indent = metadata.get('PIndent', '')
    if indent == 'Alternate':
        return 'ab'
    return 'a'


def generate_typst(metadata, poem_lines, attributions=None, template: str = 'chapBook.typ') -> str:
    title  = metadata.get('Title',  'Untitled')
    author = metadata.get('Author', 'Unknown')
    year   = metadata.get('Year',   '')
    metre  = metre_from_metadata(metadata)

    escaped = [escape_typst(ln) for ln in poem_lines]
    poem_body = '\n'.join(escaped)

    year_arg = f',\n  year: "{year}"' if year else ''

    attribution_block = ''
    if attributions:
        attribution_block = '\n' + '\n'.join(
            f'#align(right)[#emph[{escape_typst(a)}]]' for a in attributions
        ) + '\n'

    return (
        f'// Generated by mdToTypst.py\n'
        f'\n'
        f'#import "{template}": chapbook, poem\n'
        f'\n'
        f'#show: chapbook.with(\n'
        f'  title: "{title}",\n'
        f'  author: "{author}"{year_arg},\n'
        f')\n'
        f'\n'
        f'== {title}\n'
        f'\n'
        f'#poem("\n'
        f'{poem_body}\n'
        f'", metre: "{metre}")\n'
        f'{attribution_block}'
    )


# ── Entry point ─────────────────────────────────────────────────────────────

def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    input_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) >= 3 else (
        os.path.splitext(input_path)[0] + '.typ'
    )

    with open(input_path, 'r') as f:
        content = f.read()

    metadata, body = parse_front_matter(content)
    poem_lines, attributions = extract_poem_lines(body)

    if not poem_lines:
        print(
            "Warning: no poem content found — is there a @@poem or @@poem:start directive?",
            file=sys.stderr,
        )

    typst_src = generate_typst(metadata, poem_lines, attributions)

    with open(output_path, 'w') as f:
        f.write(typst_src)

    print(f"Written → {output_path}")


if __name__ == '__main__':
    main()
